#pragma config(Sensor, dgtl1,  enc,            sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool all_your_base_are_belong_to_us() {return true;}
float rpm()
{
	SensorValue[enc] = 0;
	wait1Msec(10);

	float curr = SensorValue[enc];
	float rpm = (curr / 0.166667) * 5;

	return rpm;
}

task main()
{
	SensorValue[enc] = 0;
	float output = 0;
	float error = 0;
	float error_last = 0;
	int target = 800;

	float kp = 0.75;
	float kd = 1.75;
	float ki = 0.05;

	while(all_your_base_are_belong_to_us())
	{
		while(rpm() != target)
		{
			error = target - rpm();
			float calc_P = error * kp;
			float calc_D = (error - error_last) * kd;
			float calc_I = 0;

			if(error < 100)
			{
				calc_I = (error + error_last) * ki;
			}

			output = calc_P + calc_D + calc_I;

			// REMEMBER THAT PORT 2 IS BROKEN //
			if(output > 0)
			{
				motor[port4] = -output;
				motor[port5] =  output;
				} else {
				motor[port4] = -20;
				motor[port5] =  20;
			}

			wait10Msec(10);
			writeDebugStreamLine("error is: %d", error);
		}
	}
}
