#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(){
		writeDebugStreamLine("%d", SensorValue[pot]);
	}



}
